# R packages
library(shiny)
library(shinythemes)
library(MESS)
library(wmwpow)
library(WMWssp)

# R shiny GUI
ui <- fluidPage(theme = shinytheme("cosmo"),
  # App title and navigaition
  navbarPage(
    "Select calculation:",
    tabPanel("Normality and variance calculation",
             # User input
             sidebarPanel(
               tags$h3("Data input:"),
               textInput("var1_normality", "Variable 1:", ""),
               textInput("var2_normality", "Variable 2:", ""),
               sliderInput(inputId = "bins",
                           label = "Number of bins:",
                           min = 1,
                           max = 50,
                           value = 25),
               actionButton("example_data_normality", "Example data")
             # Body content: results of normality and variance tests
             ),
             mainPanel(
               tags$label(h3('Histogram:')),
               plotOutput('Plot'),
               tags$label(h3('Normality and equal variance results:')),
               tableOutput('tabledata_normality_variance')
               )
              ),
    
    tabPanel("Hypothesis testing and power calculation",
             # User input and options
             sidebarPanel(
               tags$h3("Data input:"),
               textInput("var1_hypothesis", "Variable 1:", ""),
               textInput("var2_hypothesis", "Variable 2:", ""),
               selectInput("type_of_test", label = "Type of test:", 
                           choices = list("Unpaired 2-tailed Student's t-test" = "unpaired_2_tailed_students_t_test",
                                          "Paired 2-tailed Student's t-test" = "paired_2_tailed_students_t_test",
                                          "Unpaired 2-tailed Welch's t-test" = "unpaired_2_tailed_welchs_t_test", 
                                          "Paired 2-tailed Welch's t-test" = "paired_2_tailed_welchs_t_test",
                                          "Unpaired 2-tailed Wilcoxon test" = "unpaired_2_tailed_wilcoxon_test",
                                          "Paired 2-tailed Wilcoxon test" = "paired_2_tailed_wilcoxon_test")),
               actionButton("example_data_hypothesis", "Example data"),
               actionButton("submitbutton", "Submit", class = "btn btn-primary"),
               tags$label(h5("Example data may not be suitable for all statistical tests. New data can be generated by selecting the Example data button"))
               ),
             #  Body content: results from hypothesis and power caluclations
             mainPanel(
               tags$label(h3('Information:')), 
               htmlOutput('contents'),
               tags$label(h3('Results:')),
               tableOutput('tabledata_mean_CI'),
               tableOutput('tabledata_hypothesis_power')
               )
             )
    )
  )


# R shiny server 
server <- function(input, output, session){
  # Example data for normality and variance calculations- normal data
  observeEvent(input$example_data_normality, {
    updateTextInput(session, "var1_normality", value = (paste(signif(rnorm(50, mean=50, sd=10), digits = 3), collapse = ", " )))
    updateTextInput(session, "var2_normality", value = (paste(signif(rnorm(50, mean=50, sd=10), digits = 3), collapse = ", " )))
  })
  
  # Example data for hypothesis and power calulcations- random data between 1-20
  observeEvent(input$example_data_hypothesis, {
    updateTextInput(session, "var1_hypothesis", value = (paste((sample(1:20, 25, replace=TRUE)), collapse = ", " )))
    updateTextInput(session, "var2_hypothesis", value = (paste((sample(2:25, 25, replace=TRUE)), collapse = ", " )))
  })
  
  data_clean <- function(varibale1, variable2){
    #'Extracts and cleans varibale 1 and 2 user input
    #'Expects: string: a list of values
    #'Modifies: All spaces, tabs and commas are replace with a comma and the string is slit, deliminator: ",". The strings are converted to a numebr and missing values are removed
    #'Returns: list of values for var1 and var2 and a concatenation of Var1 and Var2
    var1 <- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", varibale1), "," )[[1]])
    var2 <- as.numeric(strsplit(gsub("\t| |, |,| ;|;",",", variable2), ",")[[1]])
    var1 <- na.omit(var1)
    var2 <- na.omit(var2)
    return(list(var1, var2, c(var1, var2))) 
  }
  
  
  # Following code is for the first navigation tab
  # Generate histogram
  output$Plot <- renderPlot({
    # Execute only if data has been input
    if(((input$var1_normality >0) == TRUE) | ((input$var2_normality >0) == TRUE)){
      var_combined <- data_clean(input$var1_normality, input$var2_normality)[[3]]
     # Execute only if there are more than one unique number    
      if((is.na(var(var_combined)) == FALSE) &
        (var(var_combined) == 0) == FALSE){
          # Allows the user to input the desigered bin size for the histrogram
          bins <- seq(min(var_combined), max(var_combined), length.out = input$bins + 1)
          hist(var_combined, breaks= bins, xlab = "Data input", ylab= "Density",
              main = "Frequency distribution", col= "lightgray", freq = FALSE)
        }
      }
    })
  # Conduct normality and variance calculations  
  output$tabledata_normality_variance<-renderTable({
    # Execute only if data has been input
    # This stops error from showing before user can input all data
    if(((input$var1_normality >0) == TRUE) | ((input$var2_normality >0) == TRUE)){
      var_combined <- data_clean(input$var1_normality, input$var2_normality)[[3]]
      var1_normality <- data_clean(input$var1_normality, input$var2_normality)[[1]]
      var2_normality <- data_clean(input$var1_normality, input$var2_normality)[[2]]
      # Execute only if there is more than one unique number and that var1_normality and var2_normality conatin more than or equal to two characters each and five characters overall
      # This stops error from showing before user can input all data
      if(
        (is.na(var(var_combined)) == FALSE) &
        ((length(var_combined) >= 3) == TRUE) &
        ((length(var1_normality) >= 2) == TRUE) &
        ((length(var2_normality) >= 2) == TRUE) &
        ((length(var_combined) >= 5) == TRUE)
      ){
        # Conduct normality and variance calculations and create a dataframe
        # Variance calculations require a minimum number of unique vales for each variable
        normality_result<- signif(shapiro.test(var_combined)[["p.value"]], digits = 3)
        variance_result<-  signif(var.test(var1_normality, var2_normality)[["p.value"]], digits = 3)
        df <- data.frame(
          Normality =  paste(normality_result, collapse = ", "),
          Equal_variance = paste(variance_result, collapse = ", "))
        colnames(df)<- c("Normality", "Equal variance")
        df <- df
      }else{
        # Normality calculations do not require a minimum number of unique values for each varibale 
        normality_result<- signif(shapiro.test(var_combined)[["p.value"]], digits = 3)
        df <- data.frame(Normality =  paste(normality_result, collapse = ", "))
        colnames(df)<- c("Normality")
        df <- df
        }
      }
    })
  
  # Following code is for the second navigation tab 
  # Mean and confidence interval calulations
  datasetInput <- reactive({
    var1_hypothesis <- data_clean(input$var1_hypothesis, input$var2_hypothesis)[[1]]
    var2_hypothesis <- data_clean(input$var1_hypothesis, input$var2_hypothesis)[[2]]
    var1_hypothesis_mean<- mean(var1_hypothesis)
    var2_hypothesis_mean<- mean(var2_hypothesis)
    #  Calculate confidence interval using selected test
    if ((input$type_of_test == "unpaired_2_tailed_students_t_test")|
        (input$type_of_test == "paired_2_tailed_students_t_test")|
        (input$type_of_test == "unpaired_2_tailed_welchs_t_test")|
        (input$type_of_test == "paired_2_tailed_welchs_t_test")){
      var1_hypothesis_CI<- signif(t.test(var1_hypothesis, conf.level = 0.95)[["conf.int"]], digits = 3)
      var2_hypothesis_CI<- signif(t.test(var2_hypothesis, conf.level = 0.95)[["conf.int"]], digits = 3)
    }
    if ((input$type_of_test == "unpaired_2_tailed_wilcoxon_test")|
        (input$type_of_test == "paired_2_tailed_wilcoxon_test")){
      var1_hypothesis_CI<- signif(wilcox.test(var1_hypothesis, conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
      var2_hypothesis_CI<- signif(wilcox.test(var2_hypothesis, conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
    }
    # Create dataframe  
    df <- data.frame(
      Variable = c("1","2"),
      Mean = c(var1_hypothesis_mean,var2_hypothesis_mean),
      Confidence_intervals =  c(paste(var1_hypothesis_CI, collapse = ", "), paste(var2_hypothesis_CI, collapse = ", "))
      
    )
    colnames(df)<- c("Variable", "Mean", "Confidence intervals")
    df <- df
  })
  # Display results from mean and confidence interval calculations when the submitbutton has been selected
  output$tabledata_mean_CI <- renderTable({
      if (input$submitbutton>0) { 
        isolate(datasetInput()) 
      } 
    })
  # Hypothesis and power calculations
  datasetInput_2 <- reactive({  
    var1_hypothesis <- data_clean(input$var1_hypothesis, input$var2_hypothesis)[[1]]
    var2_hypothesis <- data_clean(input$var1_hypothesis, input$var2_hypothesis)[[2]]
    var1_hypothesis_mean<- mean(var1_hypothesis)
    var2_hypothesis_mean<- mean(var2_hypothesis)
    var1_hypothesis_sd<- sd(var1_hypothesis)
    var2_hypothesis_sd<- sd(var2_hypothesis)
    # Defined formula 
    cohens_d<- signif((abs(var1_hypothesis_mean-var2_hypothesis_mean))/sqrt( ((var1_hypothesis_sd^2)+(var2_hypothesis_sd^2))/2), digits = 3)
    # Data preparation for power calculation
    # Calculate the sample size and sample size ratio so that the lowest sample size is taken, and the ratio is always >=1
    if(length(var1_hypothesis) == length(var2_hypothesis)){
      power_n<- as.numeric(length(var1_hypothesis))
      power_n_ratio<- length(var1_hypothesis)/length(var2_hypothesis)
    }else if(length(var1_hypothesis) > length(var2_hypothesis)){
      power_n<- as.numeric(length(var2_hypothesis))
      power_n_ratio<- length(var1_hypothesis)/length(var2_hypothesis)
    }else if(length(var1_hypothesis) < length(var2_hypothesis)){
      power_n<- as.numeric(length(var1_hypothesis))
      power_n_ratio<- length(var2_hypothesis)/length(var1_hypothesis)
    }
    # Calculate the standard deviation and standard deviation ratio so that the lowest standard deviation is taken, and the ratio is always >=1
    if(var1_hypothesis_sd == var2_hypothesis_sd){
      power_sd<- var1_hypothesis_sd
      power_sd_ratio<- var1_hypothesis_sd/var2_hypothesis_sd
    }else if(var1_hypothesis_sd > var2_hypothesis_sd){
      power_sd<- var2_hypothesis_sd
      power_sd_ratio<- var1_hypothesis_sd/var2_hypothesis_sd
    }else if(var1_hypothesis_sd < var2_hypothesis_sd){
      power_sd<- var1_hypothesis_sd
      power_sd_ratio<- var2_hypothesis_sd/var1_hypothesis_sd
    }
    
    ttest_template <- function(type_defined, paired_defined, var_defined, df_method_defined){
      #'Conducts paired or unpaird Student's or Welche's t-test
      #'Expects: type_defined="two.sample" or "one.sample" , paired_defined=TRUE or FALSE, var_defined=TRUE OR FALSE, df_method_defined="classical" or "welch"
      #'Modifies: none
      #'Returns: number: confidence intervals, p.value, power, ideal sample size
      test_CI<- signif(t.test(var1_hypothesis, var2_hypothesis, paired = paired_defined, var.equal = var_defined, alternative = "two.sided", conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(t.test(var1_hypothesis, var2_hypothesis, paired = paired_defined, var.equal = var_defined, alternative = "two.sided", conf.level = 0.95)[["p.value"]], digits = 3)
      power_result<- power_t_test(n = power_n, delta = (abs((var1_hypothesis_mean-var2_hypothesis_mean))), sd = power_sd, sig.level = 0.05, power = NULL, ratio = power_n_ratio, sd.ratio = power_sd_ratio, 
                                  type = type_defined, alternative = "two.sided", df.method = df_method_defined)
      power_result<- signif(power_result$power, digits = 3)
      # If power is equal to 100%, do not calculate ideal sample size- print "NA"
      if(power_result < 1){
        sample_size_result<- power_t_test(n = NULL, delta = (abs((var1_hypothesis_mean-var2_hypothesis_mean))), sd = power_sd, sig.level = 0.05, power = 0.8, ratio = 1, sd.ratio = power_sd_ratio, 
                                          type = "two.sample", alternative = "two.sided", df.method = df_method_defined)
        sample_size_result<- round(sample_size_result$n, digits = 0)
        sample_size_result<- paste(sample_size_result, sample_size_result, sep = ", ")[[1]]
      }else{
        sample_size_result<- paste("NA")
      }
      return(list(test_CI, test_p_value, power_result, sample_size_result))
    }
    
    wilcox_template <- function(paired_defined){
      #'Conducts paired or unpaird wilcox test
      #'Expects: paired_defined=TRUE or FALSE
      #'Modifies: none
      #'Returns: number: confidence intervals, p.value, power, ideal sample size
      test_CI<- signif(wilcox.test(var1_hypothesis, var2_hypothesis, paired = paired_defined, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)[["conf.int"]], digits = 3)
      test_p_value<- signif(wilcox.test(var1_hypothesis, var2_hypothesis, paired = paired_defined, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)[["p.value"]], digits = 3)
      invisible(capture.output(
        power_result<- shiehpow(n=(as.numeric(length(var1_hypothesis))), m=(as.numeric(length(var2_hypothesis))), p=1-test_p_value, alpha = 0.05, dist = "norm", sides = "two.sided")
      ))
      power_result<- signif(power_result$power, digits = 3)
      sample_size_result<- WMWssp(var1_hypothesis, var2_hypothesis, alpha = 0.05, power = 0.8, t = 0.5)
      sample_size_result<- paste(c(((sample_size_result$N)/2),((sample_size_result$N)/2)), collapse = ", ")[[1]]
      return(list(test_CI, test_p_value, power_result, sample_size_result))
    }
    
    
    # Hypothesis testing and power calculations by unpaired 2-tailed Student's t-test
    if (input$type_of_test == "unpaired_2_tailed_students_t_test"){
      result <- ttest_template(type_defined="two.sample" , paired_defined=FALSE, var_defined=TRUE, df_method_defined="classical")
      test_CI <- result[[1]]
      test_p_value <- result[[2]]
      power_result <- result[[3]]
      sample_size_result <- result[[4]]
  }
    # Hypothesis testing and power calculations by paired 2-tailed Student's t-test
    if (input$type_of_test == "paired_2_tailed_students_t_test"){
      result <- ttest_template(type_defined="two.sample" , paired_defined=TRUE, var_defined=TRUE, df_method_defined="classical")
      test_CI <- result[[1]]
      test_p_value <- result[[2]]
      power_result <- result[[3]]
      sample_size_result <- result[[4]]
    }
    # Hypothesis testing and power calculations by unpaired 2-tailed Welch's t-test
    if (input$type_of_test == "unpaired_2_tailed_welchs_t_test"){
      result <- ttest_template(type_defined="two.sample" , paired_defined=FALSE, var_defined=FALSE, df_method_defined="welch")
      test_CI <- result[[1]]
      test_p_value <- result[[2]]
      power_result <- result[[3]]
      sample_size_result <- result[[4]]
    }
    # Hypothesis testing and power calculations by paired 2-tailed Welch's t-test
    if (input$type_of_test == "paired_2_tailed_welchs_t_test"){
      result <- ttest_template(type_defined="two.sample" , paired_defined=TRUE, var_defined=FALSE, df_method_defined="welch")
      test_CI <- result[[1]]
      test_p_value <- result[[2]]
      power_result <- result[[3]]
      sample_size_result <- result[[4]]
    }
    # Hypothesis testing and power calculations by unpaired wilcoxon mann whitney U test 
    if (input$type_of_test == "unpaired_2_tailed_wilcoxon_test"){
      result <- wilcox_template(paired_defined=FALSE)
      test_CI <- result[[1]]
      test_p_value <- result[[2]]
      power_result <- result[[3]]
      sample_size_result <- result[[4]]
    }
    # Hypothesis testing and power calculations by paired wilcoxon mann whitney U test 
    if (input$type_of_test == "paired_2_tailed_wilcoxon_test"){
      result <- wilcox_template(paired_defined=TRUE)
      test_CI <- result[[1]]
      test_p_value <- result[[2]]
      power_result <- result[[3]]
      sample_size_result <- result[[4]]
    }
    # Create data fram from calculated statistics
    df <- data.frame(
      Confidence_intervals =  paste(test_CI, collapse = ", "),
      Cohens_d = paste(cohens_d, collapse = ", "),
      P_value = paste(test_p_value, collapse = ", "),
      Power = paste(power_result, collapse = ", "),
      Sample_size = paste(sample_size_result, collapse = ", ")
    )
    colnames(df) <- c("Confidence intervals", "Cohen's d", "P value", "Power", "Sample size")
    df <- df
  })
  # Generate hypothesis testing and power calculation data frame if submitbutton has been selected
  output$tabledata_hypothesis_power <- renderTable({
    if (input$submitbutton>0){ 
      isolate(datasetInput_2()) 
    } 
  })
  # Information regarding selected statistical test
  output$contents <- renderPrint({
      return(
        if(input$type_of_test == "unpaired_2_tailed_students_t_test"){
          return("Unpaired two-tailed Student's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        } else if (input$type_of_test == "paired_2_tailed_students_t_test"){
          return("Paired two-tailed Student's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "unpaired_2_tailed_welchs_t_test"){
          return("Unpaired two-tailed Welch's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "paired_2_tailed_welchs_t_test"){
          return("Paired two-tailed Welch's t-test will be conducted using R: t.test and power_t_test. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "unpaired_2_tailed_wilcoxon_test"){
          return("Unpaired two-tailed WMW test will be conducted using R: wilcox.test, shiehpow, and WMWssp. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }else if (input$type_of_test == "paired_2_tailed_wilcoxon_test"){
          return("Paired two-tailed WMW test will be conducted using R: R: wilcox.test, shiehpow, and WMWssp. Code adapted from Sultan et al., 2021 (https://doi.org/10.3389/fcell.2021.726281)")
        }
      ) 
    })
}
  
# Coupling of shiny UI and Server
shinyApp(ui = ui, server = server)
